import type { CrqReviewResponse } from "../types/crqWorflow.types";

export const mockCrqResponse: CrqReviewResponse = {
  plans: [
    {
      planNumber: "PTN/AC/SFP-A/MOB/04092025/019",
      planType: "Back Bone Link Upgradation",
      description: "Extend the 1+1 OH to GMSC from HYD_BCLAP_UPL_A_E30523 I7-4  & I8-4",
      crqs: [
        {
          crqNo: "CRQ000000888888",
          crqRaisedDate: "2026-02-05T11:18:45",
          description: "Extend the 1+1 OH to GMSC from HYD_BCLAP_UPL_A_E30523 I7-4  & I8-4",
          crqStatus: "Canceled",
          remark: "tre",
          crqId: 1770270525,
          managerChange: "NA",
          firstName: null,
          lastName: null,
          company: null,
          ascpy: "Bharti Airtel Ltd-TNG",
          asorg: "TX",
          asgrp: "NOC_SE",
          supportOrganization: "Operations Team",
          supportGroupName: "RSS_OPS_South",
          categorizationTier_1: "Backbone",
          categorizationTier_2: "Business",
          categorizationTier_3: "Optical patching - customer handover",
          requestedStartDate: "2017-05-24T12:00:00",
          requestedEndDate: "2017-05-24T18:00:00",
          detailedDescription: "Extend the 1+1 OH to GMSC from HYD_BCLAP_UPL_A_E30523 I7-4  & I8-4",
          aschg: "Brijesh Aggarwal",
          remedyChangeImpact: "Non Service Affecting",
          neLabel: "KNJ-BCLUE-NAS-T5-ER127.171",
          planType: "Back Bone Link Upgradation",
          planNumber: "PTN/AC/SFP-A/MOB/04092025/019",
          taskId: "PTN/AC/SFP-A/MOB/04092025/019_TASK_002",
          planActivityDetails: "new_equipment_activity",
          activitySequence: "new_equipment_activity",
          locationCodeM6: "KNJ/NAS/001",
          taskProfileType: "OPERATIONS,IMPLEMENTATION",
          state: "NEW",
          assignedGroup: "Tx-NOC SE",
          assignedDepartment: "NOC-Implementation",
          nodeType: "Discovered",
          vendor: "ECI",
          activityPlanStartDate: "2025-04-30T08:01:00",
          activityPlanEndDate: "2025-04-30T10:01:00",
          impactStartDate: "2026-02-12T12:33:17",
          impactAnalysisStatus: "In Progress",
          olmidImpactAnalysis: "B0266821",
          impactEndDate: "2026-02-12T12:33:16",
          tasks: [
            {
              taskId: "PTN/AC/SFP-A/MOB/04092025/019_TASK_002",
              neLabel: "KNJ-BCLUE-NAS-T5-ER127.171",
              planActivityDetails: "new_equipment_activity",
              activitySequence: "new_equipment_activity",
              taskProfileType: "OPERATIONS,IMPLEMENTATION",
              locationCodeM6: "KNJ/NAS/001",
              workAreaTerritory: "KANNAUJ-KNJ",
              activityPlanStartDate: "2025-04-30T08:01:00",
              activityPlanEndDate: "2025-04-30T10:01:00",
              taskActivity: "new_equipment_activity",
            },
          ],
        },
        {
          crqNo: "CRQ000000888878",
          crqRaisedDate: "2026-02-06T16:48:51",
          description: "Extend the 1+1 OH to GMSC from HYD_BCLAP_UPL_A_E30523 I7-4  & I8-4",
          crqStatus: "In Progress",
          remark: null,
          crqId: 1770376731,
          managerChange: "NA",
          firstName: null,
          lastName: null,
          company: null,
          ascpy: "Bharti Airtel Ltd-TNG",
          asorg: "TX",
          asgrp: "NOC_SE",
          supportOrganization: "Operations Team",
          supportGroupName: "RSS_OPS_South",
          categorizationTier_1: "Backbone",
          categorizationTier_2: "Business",
          categorizationTier_3: "Optical patching - customer handover",
          requestedStartDate: "2017-05-24T12:00:00",
          requestedEndDate: "2017-05-24T18:00:00",
          detailedDescription: "Extend the 1+1 OH to GMSC from HYD_BCLAP_UPL_A_E30523 I7-4  & I8-4",
          aschg: "Brijesh Aggarwal",
          remedyChangeImpact: "Non Service Affecting",
          neLabel: "KNJ-BCLUE-NAS-T5-ER127.171",
          planType: "SFP Addition",
          planNumber: "PTN/AC/SFP-A/MOB/04092025/019",
          taskId: "PTN/AC/SFP-A/MOB/04092025/019_TASK_002",
          planActivityDetails: "new_equipment_activity",
          activitySequence: "new_equipment_activity",
          locationCodeM6: "KNJ/NAS/001",
          taskProfileType: "OPERATIONS,IMPLEMENTATION",
          state: "NEW",
          assignedGroup: "Tx-NOC SE",
          assignedDepartment: "NOC-Implementation",
          nodeType: "Discovered",
          vendor: "ECI",
          activityPlanStartDate: "2025-04-30T08:01:00",
          activityPlanEndDate: "2025-04-30T10:01:00",
          impactStartDate: "2026-03-24T14:56:56",
          impactAnalysisStatus: "In Progress",
          olmidImpactAnalysis: null,
          impactEndDate: "2026-03-24T14:56:55",
          tasks: [
            {
              taskId: "PTN/AC/SFP-A/MOB/04092025/019_TASK_002",
              neLabel: "KNJ-BCLUE-NAS-T5-ER127.171",
              planActivityDetails: "new_equipment_activity",
              activitySequence: "new_equipment_activity",
              taskProfileType: "OPERATIONS,IMPLEMENTATION",
              locationCodeM6: "KNJ/NAS/001",
              workAreaTerritory: "KANNAUJ-KNJ",
              activityPlanStartDate: "2025-04-30T08:01:00",
              activityPlanEndDate: "2025-04-30T10:01:00",
              taskActivity: "new_equipment_activity",
            },
          ],
        },
      ],
    },
  ],
};