import type { User } from "../types/user";

// ─── Mock Data (unchanged core fields; additive fields feed the new UI) ─────
export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "Prasann Shrivastava",
    employeeId: "B0093363",
    function: "IP Core",
    role: "Team Lead",
    email: "prasann@corp.com",
    joinedDate: "Jan 2021",
    active: true,
    phone: "+91 98765 43210",
    manager: "Akash Sharma",
    designation: "Senior Network Lead",
    lastLogin: "2026-06-30T09:12:00",
    permissions: ["View Reports", "Manage Tasks", "Approve Changes"],
    devices: [
      { name: "Windows PC", type: "Desktop", lastActive: "2 hours ago" },
      { name: "iPhone 14", type: "Mobile", lastActive: "1 day ago" },
    ],
    sessions: [
      {
        id: "s1",
        location: "Mumbai, IN",
        ip: "103.21.244.10",
        device: "Chrome / Windows",
        time: "Today, 9:12 AM",
      },
    ],
    activity: [
      { id: "a1", action: "Approved CRQ-4521", time: "3 hours ago" },
      { id: "a2", action: "Updated schedule for IP Core", time: "1 day ago" },
    ],
  },
  {
    id: "2",
    name: "Pankaj Chaudhary",
    employeeId: "B0223564",
    function: "IP Core",
    role: "Team Lead",
    email: "pankaj@corp.com",
    joinedDate: "Mar 2021",
    active: true,
    phone: "+91 98765 11223",
    manager: "Akash Sharma",
    designation: "Network Lead",
    lastLogin: "2026-06-29T17:45:00",
    permissions: ["View Reports", "Manage Tasks"],
    devices: [{ name: "MacBook Pro", type: "Desktop", lastActive: "5 hours ago" }],
    sessions: [
      {
        id: "s2",
        location: "Pune, IN",
        ip: "103.21.244.55",
        device: "Safari / macOS",
        time: "Yesterday, 5:45 PM",
      },
    ],
    activity: [{ id: "a3", action: "Created new task group", time: "5 hours ago" }],
  },
  {
    id: "3",
    name: "Dhananjay Saini",
    employeeId: "B0223641",
    function: "IP Core",
    role: "Team Lead",
    email: "dhananjay@corp.com",
    joinedDate: "Mar 2021",
    active: true,
    phone: "+91 98765 33445",
    manager: "Akash Sharma",
    designation: "Network Lead",
    lastLogin: "2026-06-28T11:20:00",
    permissions: ["View Reports", "Manage Tasks"],
    devices: [{ name: "Windows PC", type: "Desktop", lastActive: "1 day ago" }],
    sessions: [],
    activity: [{ id: "a4", action: "Reviewed impact analysis", time: "2 days ago" }],
  },
  {
    id: "4",
    name: "Akash Sharma",
    employeeId: "B0308597",
    function: "IP Core",
    role: "Super Admin",
    email: "akash@corp.com",
    joinedDate: "Jun 2022",
    active: true,
    phone: "+91 98765 55667",
    manager: "—",
    designation: "Head of IP Core",
    lastLogin: "2026-07-01T08:05:00",
    permissions: ["Full Access", "User Management", "System Settings"],
    devices: [
      { name: "Windows PC", type: "Desktop", lastActive: "Just now" },
      { name: "iPad Pro", type: "Tablet", lastActive: "3 days ago" },
    ],
    sessions: [
      {
        id: "s3",
        location: "Delhi, IN",
        ip: "103.21.244.90",
        device: "Edge / Windows",
        time: "Today, 8:05 AM",
      },
    ],
    activity: [
      { id: "a5", action: "Added new user Riya Mehta", time: "6 hours ago" },
      { id: "a6", action: "Updated role permissions", time: "1 day ago" },
    ],
  },
  {
    id: "5",
    name: "Harsh Yadav",
    employeeId: "B0266821",
    function: "IP Core",
    role: "Team Member",
    email: "harsh@corp.com",
    joinedDate: "Aug 2021",
    active: true,
    phone: "+91 98765 77889",
    manager: "Prasann Shrivastava",
    designation: "Network Engineer",
    lastLogin: "2026-06-27T14:30:00",
    permissions: ["View Reports"],
    devices: [{ name: "Windows PC", type: "Desktop", lastActive: "3 days ago" }],
    sessions: [],
    activity: [{ id: "a7", action: "Submitted change request", time: "3 days ago" }],
  },
  {
    id: "6",
    name: "Satydeep Jaiswal",
    employeeId: "B0321549",
    function: "IP Core",
    role: "Team Member",
    email: "satydeep@corp.com",
    joinedDate: "Sep 2022",
    active: false,
    phone: "+91 98765 99001",
    manager: "Pankaj Chaudhary",
    designation: "Network Engineer",
    lastLogin: "2026-05-14T10:00:00",
    permissions: ["View Reports"],
    devices: [],
    sessions: [],
    activity: [{ id: "a8", action: "Account marked inactive", time: "6 weeks ago" }],
  },
  {
    id: "7",
    name: "Bibhu Raj",
    employeeId: "B0325609",
    function: "IP Core",
    role: "Team Member",
    email: "bibhu@corp.com",
    joinedDate: "Oct 2022",
    active: true,
    phone: "+91 98765 22110",
    manager: "Dhananjay Saini",
    designation: "Network Engineer",
    lastLogin: "2026-06-30T16:10:00",
    permissions: ["View Reports"],
    devices: [{ name: "Android Phone", type: "Mobile", lastActive: "10 mins ago" }],
    sessions: [
      {
        id: "s4",
        location: "Bengaluru, IN",
        ip: "103.21.244.31",
        device: "Chrome / Android",
        time: "Today, 4:10 PM",
      },
    ],
    activity: [{ id: "a9", action: "Logged in", time: "10 mins ago" }],
  },
  {
    id: "8",
    name: "Aditya Guleria",
    employeeId: "A1KQODMV",
    function: "IP Core",
    role: "Team Member",
    email: "aditya@corp.com",
    joinedDate: "Nov 2022",
    active: true,
    phone: "+91 98765 44556",
    manager: "Prasann Shrivastava",
    designation: "Network Engineer",
    lastLogin: "2026-06-26T09:40:00",
    permissions: ["View Reports"],
    devices: [{ name: "Windows PC", type: "Desktop", lastActive: "4 days ago" }],
    sessions: [],
    activity: [{ id: "a10", action: "Updated profile details", time: "4 days ago" }],
  },
  {
    id: "9",
    name: "Riya Mehta",
    employeeId: "B0410023",
    function: "IP Core",
    role: "Team Member",
    email: "riya@corp.com",
    joinedDate: "Jan 2023",
    active: true,
    phone: "+91 98765 66778",
    manager: "Akash Sharma",
    designation: "Network Engineer",
    lastLogin: "2026-06-30T12:00:00",
    permissions: ["View Reports"],
    devices: [{ name: "MacBook Air", type: "Desktop", lastActive: "1 hour ago" }],
    sessions: [
      {
        id: "s5",
        location: "Hyderabad, IN",
        ip: "103.21.244.72",
        device: "Chrome / macOS",
        time: "Today, 12:00 PM",
      },
    ],
    activity: [{ id: "a11", action: "Completed onboarding", time: "6 months ago" }],
  },
  {
    id: "10",
    name: "Vikram Nair",
    employeeId: "B0412088",
    function: "IP Core",
    role: "Team Lead",
    email: "vikram@corp.com",
    joinedDate: "Feb 2023",
    active: false,
    phone: "+91 98765 88990",
    manager: "Akash Sharma",
    designation: "Network Lead",
    lastLogin: "2026-04-02T08:15:00",
    permissions: ["View Reports", "Manage Tasks"],
    devices: [],
    sessions: [],
    activity: [{ id: "a12", action: "Account marked inactive", time: "3 months ago" }],
  },
];
